platform: Any CPU
configuration: Release

build:
    project: RaidPuzzler.sln
    verbosity: minimal

after_build:
    ps: 7z a -mx8 -m0=BCJ -m1=LZMA2 -mmt8 -tzip -r -y RaidPuzzler.7z '.\RaidPuzzler\bin\Release\*'

artifacts:
    - path: RaidPuzzler.7z
      name: RaidPuzzler

deploy:
    - provider: Webhook
      url: https://app.signpath.io/API/v1/0b1237fd-5307-4b83-ae70-d6a0dc0cea19/Integrations/AppVeyor?ProjectKey=raid_puzzler&SigningPolicyKey=sign_raid_puzzler
      authorization:
        secure: KiBRw03cnBHoNt+O5Oe6YA7XVivZWK4XEwgopMXaS+CiIP60LvIYrseHJ72G9ND2Q4iOlk2LgkaDXdVtzXTBDw==